// <auto-generated />
namespace Gestao_Ouvidoria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addArquivoPostmodelRespostaManifestacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addArquivoPostmodelRespostaManifestacao));
        
        string IMigrationMetadata.Id
        {
            get { return "202103282224492_add-ArquivoPost-model-RespostaManifestacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
