// <auto-generated />
namespace Gestao_Ouvidoria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AlteracaotipoCursoeCampus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteracaotipoCursoeCampus));
        
        string IMigrationMetadata.Id
        {
            get { return "202103252119280_Alteracao-tipo-Curso-e-Campus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
